# Debian based python container
FROM python:3.12-slim
LABEL author="jsamis"
ENV PYTHONUNBUFFERED True

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src

EXPOSE 4000

# TODO: Might need to test this cmd further, having issues with file sys 
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4000", "--proxy-headers"]
